print("initating startup prcess")
print("hello i am your intervew bot")
name=input("hello potental empoloyee what is your name? :>")
print(f"hello {name}")
years = int(input("how many years of exsperence do you have:>"))
if years <= 3:
    print("you do not qualify for this job")
    exit()
sallery = int(input("what is your desird sallery:>"))
if sallery >= 1000000:
    print ("NO GREEDY WE DONT LIKE YOUR KIND")
    exit()
reasion = input("why do you want to work with us?:>")
programing_reasion = input("why do you want to be a programer:>")
pen = input("sell me this pen:>")
fizz_buzz = input("how would you make fizz buzz in python do not give me the code:>")
criminal_record = int(input("do you have a criminal record 1 for yes 2 for no:>"))
if criminal_record == 1:
    print("WE DONT LIKE YOU KIND")
    exit()
work_style = input("how do you like working with others:>")
why_did_they_leave = input("why did you leave your curent job:>")
print(f"""to summurise this your name is {name} with {years} work exsperence. your exspected sallery is {sallery} you want to work with us for {reasion} and like programing beacuse{programing_reasion}
you dont have a criminal record you and you left your last job beacuse{why_did_they_leave}""")
print("we will reach out to you for further steps.")